In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import torch
import cv2
import nltk
import sklearn

In [5]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
holidays_events = pd.read_csv('holidays_events.csv')
oil = pd.read_csv('oil.csv')
stores = pd.read_csv('stores.csv')
transactions = pd.read_csv('transactions.csv')

In [6]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 28512 entries, 0 to 28511
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           28512 non-null  int64
 1   date         28512 non-null  str
 2   store_nbr    28512 non-null  int64
 3   family       28512 non-null  str
 4   onpromotion  28512 non-null  int64
dtypes: int64(3), str(2)
memory usage: 1.1 MB

In [7]:
test.describe()

                 id     store_nbr   onpromotion
count  2.851200e+04  28512.000000  28512.000000
mean   3.015144e+06     27.500000      6.965383
std    8.230850e+03     15.586057     20.683952
min    3.000888e+06      1.000000      0.000000
25%    3.008016e+06     14.000000      0.000000
50%    3.015144e+06     27.500000      0.000000
75%    3.022271e+06     41.000000      6.000000
max    3.029399e+06     54.000000    646.000000

In [8]:
test.head()

        id        date  store_nbr      family  onpromotion
0  3000888  2017-08-16          1  AUTOMOTIVE            0
1  3000889  2017-08-16          1   BABY CARE            0
2  3000890  2017-08-16          1      BEAUTY            2
3  3000891  2017-08-16          1   BEVERAGES           20
4  3000892  2017-08-16          1       BOOKS            0

In [9]:
test.tail()

            id        date  store_nbr                      family  onpromotion
28507  3029395  2017-08-31          9                     POULTRY            1
28508  3029396  2017-08-31          9              PREPARED FOODS            0
28509  3029397  2017-08-31          9                     PRODUCE            1
28510  3029398  2017-08-31          9  SCHOOL AND OFFICE SUPPLIES            9
28511  3029399  2017-08-31          9                     SEAFOOD            0

In [10]:
test.sample()

           id        date  store_nbr        family  onpromotion
5555  3006443  2017-08-19         15  FROZEN FOODS           13

In [11]:
test.shape

(28512, 5)

In [12]:
test.dtypes

id             int64
date             str
store_nbr      int64
family           str
onpromotion    int64
dtype: object

In [13]:
test.columns

Index(['id', 'date', 'store_nbr', 'family', 'onpromotion'], dtype='str')

In [14]:
test.index

RangeIndex(start=0, stop=28512, step=1)